### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/xlanguage#10]
Warning: Declaration of XoopsModules/Xlanguage/LanguageHandler::insert(XoopsModules/Xlanguage/Blanguage $lang) should be compatible with XoopsObjectHandler::insert(XoopsObject $object) in file /modules/xlanguage/class/LanguageHandler.php line 0

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28

**Comment by alain01** [comment]
maybe same error : 

Avertissement: Declaration of XoopsModules/Xlanguage/LanguageHandler::insert(XoopsModules/Xlanguage/Blanguage $lang) should be compatible with XoopsObjectHandler::insert(XoopsObject $object) dans le fichier /modules/xlanguage/class/LanguageHandler.php ligne 393
--


line 393 for me :-)

**Comment by alain01** [comment]
Anyway, it's an amazing module, no ? ;-)

**Comment by ggoffy** [comment]
problem is fixed
