### ISSUE TITLE
Blank link between flags on block

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/xlanguage#18]
![Capture d’écran 2021-08-13 121431](https://user-images.githubusercontent.com/5336960/129342337-1f274898-53b0-43f5-81b9-e7ed7b1710ec.png)

**Comment by mambax7** [comment]
Didn't you have a solution for it for another module? What was it? 
Can you submit a Pull Request?

**Comment by alain01** [comment]
ok, see https://github.com/XoopsModules25x/xlanguage/pull/20

**Comment by mambax7** [comment]
Thanks!
