### ISSUE TITLE
Missed index.php on the root

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/xlanguage#19]
Missed index.php on the root.
So the URL : 
https://www.mysite.fr/modules/xlanguage/
display files and directory

**Comment by alain01** [comment]
Humm not the solution...

**Comment by alain01** [comment]
And should not be present in the main menu.
I know that I can switch to "Hide" but this option should be unvailable on the page /modules/system/admin.php?fct=modulesadmin (Modules Admin).

**Comment by mambax7** [comment]
Thank you! 

Fixed in https://github.com/XoopsModules25x/xlanguage/pull/21

**Comment by alain01** [comment]
Sorry, just a stupid question:
Now, for all modules, we use index.php with this content:
```
<?php

header('HTTP/1.0 404 Not Found');

```
we get PR in the core to replace index.html by index.php.
So my question is:
Why did you use the index.html and not index.php ?
Compatibility raison ?

**Comment by mambax7** [comment]
I've tried index.php, but it was creating a blank page, while index.html was getting you back to the main site.

**Comment by geekwright** [comment]
I'll just mention that to me, it sounds like the  'hasMain' in xoops_version.php should be 0, instead of 1.

The index.php should stop with an error, but nothing should be trying to access it with a link -- that only happens because hasMain is true.

**Comment by mambax7** [comment]
Done in https://github.com/XoopsModules25x/xlanguage/pull/22

**Comment by alain01** [comment]
> I'll just mention that to me, it sounds like the 'hasMain' in xoops_version.php should be 0, instead of 1.

Thank you, I asked it here: 

> And should not be present in the main menu.
> I know that I can switch to "Hide" but this option should be unvailable on the page /modules/system/admin.php?fct=modulesadmin (Modules Admin).

Now it's perfect !
