### ISSUE TITLE
Use xlanguage-3.1.3_Final on NGINX all php will return status 404

### ISSUE THREAD

**Issue by CHCCD** [XoopsModules25x/xlanguage#25]
Use xlanguage-3.1.3_Final on NGINX all php will return status 404.
But php Can display.

**Comment by mambax7** [comment]
I don't use Nginx, so I'll need your help here - what issues are there?

**Comment by mambax7** [comment]
I installed Nginx and xLanguage seems to be working OK:
![image](https://user-images.githubusercontent.com/613686/130320754-305d933b-f35a-4b0f-9b5e-48847d4f3cf8.png)

**Comment by CHCCD** [comment]
Hi~
On F12
![language](https://user-images.githubusercontent.com/11765282/130328545-3ed07533-a07c-402b-a2db-fc67e56d705d.jpg)

**Comment by mambax7** [comment]
That doesn't help me much, as it doesn't give us any errors.  
Can you check your error logs and see if there is more information about what is missing? 
If you deactivate xLanguage, is the website working OK?

**Comment by CHCCD** [comment]
Hi~
deactivate xLanguage, the website is working OK。
I find , the file \xlanguage\preloads\index.php
The code.
`header('HTTP/1.0 404 Not Found');`
Make the module header 404.

**Comment by mambax7** [comment]
Can you delete the  \xlanguage\preloads\index.php file and see if it works?

**Comment by alain01** [comment]
Humm, the 3.1.3_Final bugs, we should click on the flag to back to a stable situation.
If i dont click on the flag, I can show my content in english and french like the module was inexistant.

**Comment by alain01** [comment]
The 3.1.2 version is more stable for me.

**Comment by CHCCD** [comment]
> Can you delete the \xlanguage\preloads\index.php file and see if it works?

Yes, delete the file,header is 200 OK.

**Comment by mambax7** [comment]
@CHCCD, thanks for letting us know that it works now. 

@alain01, are you still having problems, or was this related to the issue that you had with the module names in Admin?

**Comment by alain01** [comment]
no the 3.1.3 does not work on my site (2.5.11beta2)
3.1.2 is ok

**Comment by mambax7** [comment]
Since the issue reported by @CHCCD seems to be solved, I'll close it.

@alain01, please open a new issue and describe exactly the problems that you're having so we can try to fix them.
