### ISSUE TITLE
Traduction in the modules admin page

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/xlanguage#26]
Hi,
Xlanguage does not work on the modules page. 
See the labels:

![Capture d’écran 2021-08-22 235607](https://user-images.githubusercontent.com/5336960/130371242-567eb9bb-b730-4f46-9711-f81fbddeb873.png)

**Comment by geekwright** [comment]
Those are form entry fields where the name(s) can be changed. The hover popup appears to be correct. What isn't working?

**Comment by alain01** [comment]
For exemple, 
I should see for the xmcontent label : 

In french: Contenu 
In english: Content

It's ok in the module, for exemple, in the Breadcrumb,
I see the good label

But in the module admin page, i see:
[xfr]Contenu[/xfr][xen]Content[/xen] (like in the printscreen)

**Comment by alain01** [comment]
I mean "label", not the hover popup.

**Comment by mambax7** [comment]
In the Admin view, you're in the Edit mode, i.e. you'll see the [xfr]Contenu[/xfr][xen]Content[/xen]
As long as you see in the Frontend in the French mode the "Contenu", then you're OK and the xLanguage is worknig

**Comment by alain01** [comment]
Ok,
I believed all text was translate if we use the code [xfr][/xfr] [xen][/xen]
Never think that I was in edit mode in admin view.
Thank you for you answer.
