### ISSUE TITLE
Undefined variable: _POST

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xlanguage#3]
When I update the system (/modules/system/admin.php), I get this error:

Notice: Undefined variable: _POST in file /modules/xlanguage/api.php line 87

___

My config:

PHP version: 5.6.4-4ubuntu6.2
MYSQL version: 5.6.25-0ubuntu0.15.04.1
XOOPS version: 2.5.7.1

**Comment by mambax7** [comment]
Can't reproduce it on your system

**Comment by cesagonchu** [comment]
This bug happened when I sent the language files. Having uninstalled and reinstalled the module appears to have solved the problem.
The problems is that someone may repeat the same procedure as me: install the module, send the language files, and then update modules and core.

**Comment by mambax7** [comment]
If you provide me steps to reproduce it, I'll look into it.
