### ISSUE TITLE
problem in the change language Block URL

### ISSUE THREAD

**Issue by orwah** [XoopsModules25x/xlanguage#8]
if changing the language a couple of times from the language Block  , the URL becomes wrong :
mysite.ltd/modules/news/index.php?lang=english?lang=arabic?lang=english

need to fix
that Must from \templates\blocks\xlanguage_block.tpl
line 4 and line 20 

i guess you must change it back to :
 a href="<{$block.url}><{$lang.name}>" title="<{$lang.desc}>"

**Comment by mambax7** [comment]
Good catch. I'll fix it later today

**Comment by mambax7** [comment]
Fixed in: https://github.com/XoopsModules25x/xlanguage/releases/tag/3.05_RC-1
